src/config/routes.rb
Rails.application.routes.draw do

  # Inserts listing 'Id' into the orders url so that each listings order has a unique URL.
  # Controller then uses this unique URL to figure out which listing is being ordered so it can find the order.
  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get "pages/about"
  get "pages/contact"

  # 'Manage Listings' page. Displays all current listings the logged in user is selling.
  get "seller", to: "listings#seller"

  # Displays order history pages (the 'orders' database) for users purchased and sold items
  get "sales", to: "orders#sales"
  get "purchases", to: "orders#purchases"

  # Homepage
  root "listings#index"
end

src/app/models/listing.rb
class Listing < ApplicationRecord
  has_one_attached :productimage
  belongs_to :user
  # belongs_to :wishlist
  # Second hand marketplaces such as gumtree typically only sell individual items
  has_one :order

  validates :item, :price, :location, :description, presence: true
  validates :price, numericality: { greater_than: 0 }

  validate :image_presence
  validate :image_format

  #Scope methods
  #Scope methods (sort_by_price) are named class method for retrieving and querying objects, with a corresponding route.
  # scope :sort_by_price, -> { order("price ASC") }

  private

  def image_presence
    if productimage.attached? == false
      errors.add :productimage, "Image can't be blank"
    end
  end

  def image_format
    return unless productimage.attached?
    return if productimage.blob.content_type.start_with? "image/"
    productimage.purge_later
    errors.add :productimage, "Wrong format"
  end
end

src/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  # Authorization: for users who are NOT signed in.
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :seller]
  # Authorization: for signed in users
  before_action :check_user, only: [:edit, :update, :destroy]

  # When current_user goes to the seller page this method will only display the listings the current user owns
  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /listings
  # GET /listings.json
  # Redirect to stop users from typing in page numbers in the url where no listings exist.
  def index
    @listings = Listing.paginate(page: params[:page], per_page: 8)
    # redirect_to root_path if @listings.empty?
    # @listings.length
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @foo = "bar"
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.productimage.attach(listing_params[:productimage])
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        #15
        @listing.productimage.attach(listing_params[:productimage]) if listing_params[:productimage]
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_listing
    @listing = Listing.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def listing_params
    params.require(:listing).permit(:item, :price, :location, :description, :productimage, :user_id)
  end

  # Authorization: Checks if user owns the listing
  def check_user
    if current_user != @listing.user
      redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
    end
  end
end

src/app/helpers/listings_helper.rb
module ListingsHelper
end

src/app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>
       <div id="error_explanation" class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item, "Title" %><i><br>(Max title length is 22 characters)</i><br>
    <%= form.text_field :item, class: "form-control", :maxlength => 22 %>
  </div>

  <br>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>
  
  <br>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <br>


  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <br>

  <div>
    <%= form.label :productimage %>
    <%= form.file_field :productimage %>
  </div>

  <br>


  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

src/app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

src/app/views/listings/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>The Premier Marketplace<br>
    for Pre-loved Skydive Gear.</h1>
    <h2>Buy - Sell - Chat.  Your home away from the drop-zone.</h2>
  </div>
</div>


<h2>All Listings</h2>
<%= will_paginate @listings, class: 'pagination_bar' %>

<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="product-card">
        <%= link_to image_tag(listing.productimage, class: 'custom-thumbnail'),
        listing %>
        <div class="middle">
          <button>
            <%= link_to "View Item", listing, class: 'product-button' %>
            <div class="text"></div>
          </button>
        </div>
        <div class="caption">
          <h3><%= truncate(listing.item, length:22) %></h3>
          <p class="price"><%= number_to_currency(listing.price) %></p>
          <p><%= "Sold by #{listing.user.name}" %></p>
          <p><%= truncate(listing.location, length:36) %></p>
          <p><%= truncate(listing.description, length:75) %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<br>

src/app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

src/app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Location</th>
    <th class="center">Description</th>
    <th class="center">Action</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
     <td><%= link_to image_tag(listing.productimage, size: "175x150"), listing %></td>
     <td><%= listing.item %></td>
     <td><%= number_to_currency(listing.price) %></td>
     <td><%= listing.location %></td>
     <td><%= listing.description %></td>
     <td>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "View", listing, class: "btn btn-link" %></li>
          <li><%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %></li>
          <li><%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></li>
        </ul>
      </div>
    </td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %> 
    <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %> 
<% end %>

src/app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
        <%= image_tag @listing.productimage %>
    </div>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.item %></h3>
    <p><%= number_to_currency(@listing.price) %></p>
    <p><%= @listing.location %></p>
    <p><%= @listing.description %></p>
    <br>
    <div class="center">
      <%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary", data: { turbolinks: false } %>
    </div>
  </div>

<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> 
<% end %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>