src/config/routes.rb
Rails.application.routes.draw do

  # Inserts listing 'Id' into the orders url so that each listings order has a unique URL.
  # Controller then uses this unique URL to figure out which listing is being ordered so it can find the order.
  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get "pages/about"
  get "pages/contact"

  # 'Manage Listings' page. Displays all current listings the logged in user is selling.
  get "seller", to: "listings#seller"

  # Displays order history pages (the 'orders' database) for users purchased and sold items
  get "sales", to: "orders#sales"
  get "purchases", to: "orders#purchases"

  # Homepage
  root "listings#index"
end

src/app/views/layouts/_footer.html.erb
<!-- <p>Copyright 2019</p> -->

<footer>
        <div class="footer-row">
            <div class="col span-1-of-2">
                <ul class="footer-nav">
                    <li><%= link_to 'About Skygear', pages_about_path %></li>
                    <li><a href="#">Blog</a></li>
                    <li><%= link_to 'Contact Us', pages_contact_path %></li>
                    <li><a href="#">iOS App</a></li>
                    <li><a href="#">Android App</a></li>
                </ul>
            </div>
        </div>
            <div class="col span-1-of-2">
                <ul class="social-links">
                    <li><a href="#"><i class="ion-social-facebook"></i></a></li>
                    <li><a href="#"><i class="ion-social-twitter"></i></a></li>
                    <li><a href="#"><i class="ion-social-googleplus"></i></a></li>
                    <li><a href="#"><i class="ion-social-instagram"></i></a></li>
                </ul>
            </div>
        </div>
        <!-- <div class="row">
            <p>
                This webpage was created for the course "Design and Develop a Killer Website Using HTML5 and CSS3" by Jonas Schmedtmann. No copyrights here.<br>
                This webpage is for you! So go and do whatever you want with it and have fun.
            </p>
            <p>
                Build with <i class="ion-ios-heart" style="color: #ea0000; padding: 0 3px;"></i> in the beautiful city of Lisbon, Portugal, March 2015.
            </p> -->
        </div>
</footer>

src/app/views/layouts/_header.html.erb
<!--12-->
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Skygear', listings_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to 'About Skygear', pages_about_path %></li>
      <li><%= link_to 'Contact Us', pages_contact_path %></li>
    </ul>

    <!-- dropdown menu from bootstrap 3 documentation + user authorization -->
    <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seller Account<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Manage Listings", seller_path %></li>
          <li><%= link_to "Sales History", sales_path %></li>
          <li><%= link_to 'List Your Item', new_listing_path %></li>
        </ul>
      </li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Purchase History", purchases_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>

    <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <% end %>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</nav>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <title>Skygear</title>
</head>

<body>
<div class="footer-positioning">

  <%= render 'layouts/header' %>

<div class="container">
  <!-- Styling for notice and success alerts NOT error alerts-->
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

  <%= yield %>
</div>
</div>
  <%= render 'layouts/footer' %>

</body>
</html>